"""init_db_2

Revision ID: 1ccc7eb86081
Revises: 12a431840e56
Create Date: 2024-07-04 16:49:31.263647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccc7eb86081'
down_revision: Union[str, None] = '12a431840e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_wears_1', sa.Column('name_eng_22', sa.String(length=256), nullable=False), schema='skins')
    op.create_unique_constraint(None, 'skins_wears_1', ['name_eng_22'], schema='skins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins_wears_1', schema='skins', type_='unique')
    op.drop_column('skins_wears_1', 'name_eng_22', schema='skins')
    # ### end Alembic commands ###
