"""inherit imagemixin from namemixin

Revision ID: 1efe07f422a9
Revises: 2963d4a87248
Create Date: 2024-07-07 17:14:14.400961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efe07f422a9'
down_revision: Union[str, None] = '2963d4a87248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_case_types', sa.Column('name_rus', sa.String(length=256), nullable=False), schema='skins')
    op.add_column('skins_case_types', sa.Column('name_eng', sa.String(length=256), nullable=False), schema='skins')
    op.create_unique_constraint(None, 'skins_case_types', ['name_rus'], schema='skins')
    op.create_unique_constraint(None, 'skins_case_types', ['name_eng'], schema='skins')
    op.add_column('skins_skins', sa.Column('name_rus', sa.String(length=256), nullable=False), schema='skins')
    op.add_column('skins_skins', sa.Column('name_eng', sa.String(length=256), nullable=False), schema='skins')
    op.create_unique_constraint(None, 'skins_skins', ['name_rus'], schema='skins')
    op.create_unique_constraint(None, 'skins_skins', ['name_eng'], schema='skins')
    op.add_column('skins_sticker_types', sa.Column('name_rus', sa.String(length=256), nullable=False), schema='skins')
    op.add_column('skins_sticker_types', sa.Column('name_eng', sa.String(length=256), nullable=False), schema='skins')
    op.create_unique_constraint(None, 'skins_sticker_types', ['name_rus'], schema='skins')
    op.create_unique_constraint(None, 'skins_sticker_types', ['name_eng'], schema='skins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins_sticker_types', schema='skins', type_='unique')
    op.drop_constraint(None, 'skins_sticker_types', schema='skins', type_='unique')
    op.drop_column('skins_sticker_types', 'name_eng', schema='skins')
    op.drop_column('skins_sticker_types', 'name_rus', schema='skins')
    op.drop_constraint(None, 'skins_skins', schema='skins', type_='unique')
    op.drop_constraint(None, 'skins_skins', schema='skins', type_='unique')
    op.drop_column('skins_skins', 'name_eng', schema='skins')
    op.drop_column('skins_skins', 'name_rus', schema='skins')
    op.drop_constraint(None, 'skins_case_types', schema='skins', type_='unique')
    op.drop_constraint(None, 'skins_case_types', schema='skins', type_='unique')
    op.drop_column('skins_case_types', 'name_eng', schema='skins')
    op.drop_column('skins_case_types', 'name_rus', schema='skins')
    # ### end Alembic commands ###
