"""create database

Revision ID: 3a739d810849
Revises: 
Create Date: 2024-06-25 22:14:04.552427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a739d810849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_types',
    sa.Column('id_case_type', sa.Integer(), nullable=False),
    sa.Column('case_type_name', sa.String(), nullable=False),
    sa.Column('case_type_image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_case_type'),
    sa.UniqueConstraint('case_type_image_url'),
    sa.UniqueConstraint('case_type_name')
    )
    op.create_table('game_items',
    sa.Column('id_game_item', sa.Integer(), nullable=False),
    sa.Column('game_item_name', sa.String(), nullable=False),
    sa.Column('game_item_type', sa.Enum('rifle', 'sniper_rifle', 'pistol', 'knife', 'machine_pistol', 'machinegun', 'shotgun', 'gloves', 'sticker', 'case', name='gameitemtype'), nullable=False),
    sa.PrimaryKeyConstraint('id_game_item'),
    sa.UniqueConstraint('game_item_name')
    )
    op.create_table('rarities',
    sa.Column('id_rarity', sa.Integer(), nullable=False),
    sa.Column('rarity_name', sa.String(), nullable=False),
    sa.Column('rarity_color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_rarity'),
    sa.UniqueConstraint('rarity_name')
    )
    op.create_table('skins',
    sa.Column('id_skin', sa.Integer(), nullable=False),
    sa.Column('rarity_name', sa.Integer(), nullable=False),
    sa.Column('id_game_item', sa.Integer(), nullable=False),
    sa.Column('id_case_type', sa.Integer(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('skin_image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_case_type'], ['case_types.id_case_type'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_game_item'], ['game_items.id_game_item'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rarity_name'], ['rarities.id_rarity'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_skin'),
    sa.UniqueConstraint('skin_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('rarities')
    op.drop_table('game_items')
    op.drop_table('case_types')
    # ### end Alembic commands ###
