"""init_db

Revision ID: 2963d4a87248
Revises: 
Create Date: 2024-07-07 16:45:56.365596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2963d4a87248'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins_case_types',
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.CheckConstraint("image_url LIKE 'http%' ", name='url_validator'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    schema='skins'
    )
    op.create_table('skins_game_item_types',
    sa.Column('name_rus', sa.String(length=256), nullable=False),
    sa.Column('name_eng', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_eng'),
    sa.UniqueConstraint('name_rus'),
    schema='skins'
    )
    op.create_table('skins_rarities',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.CheckConstraint("hex_color LIKE '#%'", name='hex_color_first_letter'),
    sa.CheckConstraint('LENGTH(hex_color) = 7', name='hex_color_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='skins'
    )
    op.create_table('skins_store_items',
    sa.Column('id_owner', sa.Integer(), nullable=False),
    sa.Column('assert_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='skins'
    )
    op.create_table('skins_wear_conditions',
    sa.Column('name_rus', sa.String(length=256), nullable=False),
    sa.Column('name_eng', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_eng'),
    sa.UniqueConstraint('name_rus'),
    schema='skins'
    )
    op.create_table('skins_skins',
    sa.Column('id_rarity', sa.Integer(), nullable=False),
    sa.Column('id_game_item_type', sa.Integer(), nullable=False),
    sa.Column('id_case_type', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.CheckConstraint("image_url LIKE 'http%'", name='url_validator'),
    sa.ForeignKeyConstraint(['id_case_type'], ['skins.skins_case_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_game_item_type'], ['skins.skins_game_item_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_rarity'], ['skins.skins_rarities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    schema='skins'
    )
    op.create_table('skins_sticker_types',
    sa.Column('id_rarity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['id_rarity'], ['skins.skins_rarities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    schema='skins'
    )
    op.create_table('skins_store_skins',
    sa.Column('id_store_item', sa.Integer(), nullable=False),
    sa.Column('id_wear_condition', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.Integer(), nullable=False),
    sa.Column('skin_float', sa.Float(), nullable=False),
    sa.Column('is_stattrack', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.CheckConstraint('pattern > 0 and pattern < 1000', name='pattern_limits'),
    sa.CheckConstraint('skin_float > 0.0 and skin_float < 1.0', name='pattern_limits_2'),
    sa.ForeignKeyConstraint(['id_store_item'], ['skins.skins_store_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_wear_condition'], ['skins.skins_wear_conditions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='skins'
    )
    op.create_table('skins_store_skins_stickers',
    sa.Column('id_sticker', sa.Integer(), nullable=False),
    sa.Column('id_store_skin', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 4', name='position_min_max'),
    sa.ForeignKeyConstraint(['id_sticker'], ['skins.skins_sticker_types.id'], ),
    sa.ForeignKeyConstraint(['id_store_skin'], ['skins.skins_store_skins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skins'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins_store_skins_stickers', schema='skins')
    op.drop_table('skins_store_skins', schema='skins')
    op.drop_table('skins_sticker_types', schema='skins')
    op.drop_table('skins_skins', schema='skins')
    op.drop_table('skins_wear_conditions', schema='skins')
    op.drop_table('skins_store_items', schema='skins')
    op.drop_table('skins_rarities', schema='skins')
    op.drop_table('skins_game_item_types', schema='skins')
    op.drop_table('skins_case_types', schema='skins')
    # ### end Alembic commands ###
