"""add eng_name columns

Revision ID: 82d5d8300fa5
Revises: a466f7842018
Create Date: 2024-06-30 22:51:46.964717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d5d8300fa5'
down_revision: Union[str, None] = 'a466f7842018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins_case_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_rus', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('name_eng'),
    sa.UniqueConstraint('name_rus'),
    schema='skins'
    )
    op.create_table('skins_game_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_rus', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('rifle', 'sniper_rifle', 'pistol', 'knife', 'machine_pistol', 'machinegun', 'shotgun', 'gloves', 'sticker', 'case', name='gameitemtypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_eng'),
    sa.UniqueConstraint('name_rus'),
    schema='skins'
    )
    op.create_table('skins_rarities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hex_color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='skins'
    )
    op.create_table('skins_skins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rarity', sa.Integer(), nullable=False),
    sa.Column('id_game_item', sa.Integer(), nullable=False),
    sa.Column('id_case_type', sa.Integer(), nullable=False),
    sa.Column('name_rus', sa.String(), nullable=False),
    sa.Column('name_eng', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_case_type'], ['skins.skins_case_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_game_item'], ['skins.skins_game_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_rarity'], ['skins.skins_rarities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='skins'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins_skins', schema='skins')
    op.drop_table('skins_rarities', schema='skins')
    op.drop_table('skins_game_items', schema='skins')
    op.drop_table('skins_case_types', schema='skins')
    # ### end Alembic commands ###
