"""add GameItem model

Revision ID: 917d4247a66b
Revises: 1efe07f422a9
Create Date: 2024-07-07 17:50:16.228743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917d4247a66b'
down_revision: Union[str, None] = '1efe07f422a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins_game_items',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id_item_type', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['id_item_type'], ['skins.skins_game_item_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='skins'
    )
    op.drop_constraint('skins_skins_id_game_item_type_fkey', 'skins_skins', schema='skins', type_='foreignkey')
    op.create_foreign_key(None, 'skins_skins', 'skins_game_items', ['id_game_item_type'], ['id'], source_schema='skins', referent_schema='skins', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins_skins', schema='skins', type_='foreignkey')
    op.create_foreign_key('skins_skins_id_game_item_type_fkey', 'skins_skins', 'skins_game_item_types', ['id_game_item_type'], ['id'], source_schema='skins', referent_schema='skins', ondelete='RESTRICT')
    op.drop_table('skins_game_items', schema='skins')
    # ### end Alembic commands ###
