"""add_store_skins_fk

Revision ID: 9f60fa2fe720
Revises: 917d4247a66b
Create Date: 2024-07-21 20:42:33.957951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f60fa2fe720'
down_revision: Union[str, None] = '917d4247a66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins_store_skins', sa.Column('id_skin', sa.Integer(), nullable=False), schema='skins')
    op.create_foreign_key(None, 'skins_store_skins', 'skins_skins', ['id_skin'], ['id'], source_schema='skins', referent_schema='skins', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skins_store_skins', schema='skins', type_='foreignkey')
    op.drop_column('skins_store_skins', 'id_skin', schema='skins')
    # ### end Alembic commands ###
